import { db } from "../index.ts"; // your Drizzle client
import { leads } from "../db/schema/users.ts";

const dummyLeads = [
  {
    id: "lead1",
    name: "John Doe",
    userId: "Nzbsosreb0FsYnZgLLRGdS3csBh4UuXI",
    email: "john.doe@example.com",
    company: "Acme Corp",
    campaignName: "Summer Campaign",
    status: "Pending",
    lastContactDate: new Date("2025-09-01").toISOString(),
    phone: "+1 555 123 4567",
    notes: "Interested in product X, follow up next week",
  },
  {
    id: "lead2",
    name: "Jane Smith",
    userId: "Nzbsosreb0FsYnZgLLRGdS3csBh4UuXI",
    email: "jane.smith@example.com",
    company: "Beta Ltd",
    campaignName: "Fall Campaign",
    status: "Contacted",
    lastContactDate: new Date("2025-09-02").toISOString(),
    phone: "+1 555 987 6543",
    notes: "Requested demo, send follow-up email",
  },
  {
    id: "lead3",
    name: "Michael Johnson",
    userId: "Nzbsosreb0FsYnZgLLRGdS3csBh4UuXI",
    email: "michael.johnson@example.com",
    company: "Gamma Inc",
    campaignName: "Summer Campaign",
    status: "Responded",
    lastContactDate: new Date("2025-09-03").toISOString(),
    phone: "+1 555 111 2222",
    notes: "Positive response, schedule meeting",
  },
  {
    id: "lead4",
    name: "Emily Davis",
    userId: "sdfsf",
    email: "emily.davis@example.com",
    company: "Delta Solutions",
    campaignName: "Spring Campaign",
    status: "Converted",
    lastContactDate: new Date("2025-09-05").toISOString(),
    phone: "+1 555 333 4444",
    notes: "Closed deal, send welcome pack",
  },
  {
    id: "lead5",
    name: "Robert Wilson",
    userId: "suidhfsf",
    email: "robert.wilson@example.com",
    company: "Epsilon Co",
    campaignName: "Fall Campaign",
    status: "Pending",
    lastContactDate: new Date("2025-09-06").toISOString(),
    phone: "+1 555 555 6666",
    notes: "Follow up in two weeks",
  },
  {
    id: "lead6",
    name: "Sophia Taylor",
    userId: "abc123",
    email: "sophia.taylor@example.com",
    company: "Zeta Group",
    campaignName: "Winter Blast",
    status: "Contacted",
    lastContactDate: new Date("2025-09-07").toISOString(),
    phone: "+1 555 444 7777",
    notes: "Sent pricing details, awaiting response",
  },
  {
    id: "lead7",
    name: "Daniel Brown",
    userId: "def456",
    email: "daniel.brown@example.com",
    company: "Eta Technologies",
    campaignName: "Holiday Deals",
    status: "Converted",
    lastContactDate: new Date("2025-09-08").toISOString(),
    phone: "+1 555 222 8888",
    notes: "Signed contract, onboarding next week",
  },
  {
    id: "lead8",
    name: "Olivia Martinez",
    userId: "ghi789",
    email: "olivia.martinez@example.com",
    company: "Theta Systems",
    campaignName: "Black Friday Push",
    status: "Pending",
    lastContactDate: new Date("2025-09-09").toISOString(),
    phone: "+1 555 777 1111",
    notes: "High interest, revisit during sale",
  },
  {
    id: "lead9",
    name: "William Anderson",
    userId: "jkl321",
    email: "william.anderson@example.com",
    company: "Iota Enterprises",
    campaignName: "Cyber Monday",
    status: "Responded",
    lastContactDate: new Date("2025-09-10").toISOString(),
    phone: "+1 555 999 3333",
    notes: "Requested proposal, send docs",
  },
  {
    id: "lead10",
    name: "Isabella Thomas",
    userId: "mno654",
    email: "isabella.thomas@example.com",
    company: "Kappa LLC",
    campaignName: "Year End Clearance",
    status: "Contacted",
    lastContactDate: new Date("2025-09-11").toISOString(),
    phone: "+1 555 666 4444",
    notes: "Call scheduled for next Monday",
  },
  {
    id: "lead11",
    name: "James White",
    userId: "pqr987",
    email: "james.white@example.com",
    company: "Lambda Partners",
    campaignName: "New Year Promo",
    status: "Converted",
    lastContactDate: new Date("2025-09-12").toISOString(),
    phone: "+1 555 888 5555",
    notes: "Closed deal with discount",
  },
  {
    id: "lead12",
    name: "Mia Harris",
    userId: "stu321",
    email: "mia.harris@example.com",
    company: "Mu Services",
    campaignName: "Valentine Special",
    status: "Pending",
    lastContactDate: new Date("2025-09-13").toISOString(),
    phone: "+1 555 111 9999",
    notes: "Not ready yet, follow up in 1 month",
  },
  {
    id: "lead13",
    name: "Alexander Clark",
    userId: "vwx654",
    email: "alexander.clark@example.com",
    company: "Nu Agency",
    campaignName: "Easter Discount",
    status: "Responded",
    lastContactDate: new Date("2025-09-14").toISOString(),
    phone: "+1 555 222 0000",
    notes: "Requested feature list",
  },
  {
    id: "lead14",
    name: "Charlotte Lewis",
    userId: "yz123",
    email: "charlotte.lewis@example.com",
    company: "Xi Global",
    campaignName: "Independence Day Promo",
    status: "Contacted",
    lastContactDate: new Date("2025-09-15").toISOString(),
    phone: "+1 555 333 7777",
    notes: "Sent initial quote",
  },
  {
    id: "lead15",
    name: "Benjamin Walker",
    userId: "abc222",
    email: "benjamin.walker@example.com",
    company: "Omicron Ventures",
    campaignName: "Back to School",
    status: "Converted",
    lastContactDate: new Date("2025-09-16").toISOString(),
    phone: "+1 555 444 9999",
    notes: "Confirmed large order",
  },
  {
    id: "lead16",
    name: "Amelia Hall",
    userId: "def333",
    email: "amelia.hall@example.com",
    company: "Pi Creations",
    campaignName: "Festive Bonanza",
    status: "Pending",
    lastContactDate: new Date("2025-09-17").toISOString(),
    phone: "+1 555 555 8888",
    notes: "Said to check back after quarter ends",
  },
  {
    id: "lead17",
    name: "Ethan Allen",
    userId: "ghi444",
    email: "ethan.allen@example.com",
    company: "Rho Studios",
    campaignName: "Monsoon Deals",
    status: "Responded",
    lastContactDate: new Date("2025-09-18").toISOString(),
    phone: "+1 555 666 0000",
    notes: "Negotiating pricing terms",
  },
  {
    id: "lead18",
    name: "Harper Young",
    userId: "jkl555",
    email: "harper.young@example.com",
    company: "Sigma Enterprises",
    campaignName: "Diwali Dhamaka",
    status: "Contacted",
    lastContactDate: new Date("2025-09-19").toISOString(),
    phone: "+1 555 777 2222",
    notes: "Interested in bundle offers",
  },
  {
    id: "lead19",
    name: "Lucas King",
    userId: "mno666",
    email: "lucas.king@example.com",
    company: "Tau Network",
    campaignName: "Christmas Carnival",
    status: "Pending",
    lastContactDate: new Date("2025-09-20").toISOString(),
    phone: "+1 555 888 3333",
    notes: "Left voicemail, no reply yet",
  },
  {
    id: "lead20",
    name: "Ella Scott",
    userId: "pqr777",
    email: "ella.scott@example.com",
    company: "Upsilon Tech",
    campaignName: "Halloween Spree",
    status: "Converted",
    lastContactDate: new Date("2025-09-21").toISOString(),
    phone: "+1 555 999 4444",
    notes: "Deal closed with add-ons",
  },
];


async function seedLeads() {
  for (const lead of dummyLeads) {
    await db.insert(leads).values(lead);
  }
  console.log("Dummy leads inserted!");
}

seedLeads().catch(console.error);
